- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract file
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes

- name: Template a file to html folder
  template: 
    src: wp-config-sample.php.j2
    dest: /var/www/html/wp-config.php

- name: Restart Apache
  service:
    name: httpd
    state: restarted